services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - ./logs:/mosquitto/log

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Painel Web (Acesse via localhost:15672 - admin/admin)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  edge-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: edge-gateway
    container_name: edge_gateway
    restart: always
    environment:
      - BROKER_IP=mosquitto
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5683:5683/udp"
    volumes:
      - ./logs:/app/logs

  devices-lab1-mqtt:
    build:
      context: .
      dockerfile: Dockerfile
      target: devices
    container_name: devices_lab1_mqtt
    command: ["Lab1Mqtt"]
    restart: always
    environment:
      - BROKER_IP=mosquitto
    volumes:
      - ./logs:/app/logs

  devices-lab2-coap:
    build:
      context: .
      dockerfile: Dockerfile
      target: devices
    container_name: devices_lab2_coap
    command: ["Lab2Coap"]
    restart: always
    environment:
      - GATEWAY_IP=edge-gateway
    volumes:
      - ./logs:/app/logs

  ms-digital-twins:
    build:
      context: .
      dockerfile: Dockerfile
      target: ms-digital-twins
    container_name: ms_digital_twins
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/app/logs

  ms-laboratorio:
    build:
      context: .
      dockerfile: Dockerfile
      target: ms-laboratorio
    container_name: ms_laboratorio
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8083:8083"
    volumes:
      - ./logs:/app/logs

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-gateway
    container_name: api_gateway
    restart: always
    environment:
      # Passa o nome interno dos contentores usando o DNS do Docker Compose
      - TWINS_URL=http://ms-digital-twins:8081
      - LAB_URL=http://ms-laboratorio:8083
    ports:
      - "8080:8080" # Única porta oficial do sistema aberta para o exterior
    volumes:
      - ./logs:/app/logs

volumes:
  mosquitto_data:
  rabbitmq_data:
