FROM eclipse-mosquitto:latest

# Copy configuration file to the container
COPY config/mosquitto.conf /mosquitto/config/mosquitto.conf

# Expose MQTT port
EXPOSE 1883

# Expose Websockets port
EXPOSE 9001
